# Exported from Render on 2026-04-17T10:37:54Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: SentinelAI
      runtime: python
      repo: https://github.com/shrish0103/SentinelAI
      plan: free
      envVars:
      - key: SERVICE_TARGETS_JSON
        sync: false
      - key: HEALTH_TIMEOUT_SECONDS
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OWNER_TELEGRAM_IDS
        sync: false
      - key: RESUME_CONTEXT
        sync: false
      - key: OLLAMA_BASE_URL
        sync: false
      - key: OPENAI_BASE_URL
        sync: false
      - key: OPENROUTER_BASE_URL
        sync: false
      - key: API_KEY
        sync: false
      - key: MODEL_NAME
        sync: false
      - key: MODEL_PROVIDER
        sync: false
      - key: APP_ENV
        sync: false
      - key: APP_NAME
        sync: false
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
      autoDeployTrigger: commit
      rootDir: app
